owners:
  ubuntu: "099720109477"           # Canonical
  # amazon_linux: "137112412989"   # Amazon Linux
  # redhat: "309956199498"         # Red Hat
  # suse: "013907871322"           # SUSE
  # debian: "136693071363"         # Debian
  # windows: "801119661308"        # Microsoft Windows Server

regions:
  - "us-east-1"
  # - "us-east-2"
  # - "us-west-1"
  # - "us-west-2"
  # - "eu-west-1"
  # - "eu-west-2"
  # - "eu-west-3"
  # - "eu-central-1"
  # - "eu-north-1"
  # - "ap-south-1"
  # - "ap-south-2"
  # - "ap-northeast-1"
  # - "ap-northeast-2"
  # - "ap-northeast-3"
  # - "ap-southeast-1"
  # - "ap-southeast-2"
  # - "ap-southeast-3"
  # - "ca-central-1"
  # - "me-south-1"
  # - "me-central-1"
  # - "sa-east-1"
  # - "af-south-1"
